name: Docker
on:
  push:
    tags:
      - 'NLSR-[0-9]+*'
  schedule:
    # twice a month
    - cron: '20 9 5,20 * *'
  workflow_dispatch:

permissions:
  attestations: write
  id-token: write
  packages: write

jobs:
  nlsr:
    uses: named-data/actions/.github/workflows/docker-image.yml@v1
    with:
      name: nlsr
